### ISSUE TITLE
Prefixed C struct fields

### ISSUE THREAD

**Issue by aasmune** [UAVCAN/nunavut#196] opened 2021-03-17 19:36 UTC
**Problem description**

When generating C headers, some C struct fields are prefixed with a "_". 

DSDL definition (`foo/Foo.1.0.uavcan`):
```
bool iso
bool oro
bool ando
bool noto

bool torque
bool tisque
bool tandque
bool tnotque

@sealed
```
becomes:
```C
typedef struct
{
    /// saturated bool iso
    bool _iso;

    /// saturated bool oro
    bool oro;

    /// saturated bool ando
    bool ando;

    /// saturated bool noto
    bool noto;

    /// saturated bool torque
    bool _torque;

    /// saturated bool tisque
    bool tisque;

    /// saturated bool tandque
    bool tandque;

    /// saturated bool tnotque
    bool tnotque;
} foo_Foo_1_0;
```

This is most likely related to/duplicated by #188, which reports a similar case with prefixed folder names. 

As in #188, it does not look like the prefixing is caused by the _is_/_or_ in _iso_/_torque_ as substituting _and_/_not_ does not cause the respective fields to be prefixed.

**Comment by thirtytwobits** [comment] 2021-06-14 02:25
Yep. This is a duplicate of #188

**Closed by thirtytwobits** 2021-06-14 02:25 UTC
Labels: bug, duplicate
